# 1. Configuración Dinámica del Puerto (Vital para Railway)
server.port=${PORT:8080}

# 2. Configuración Dinámica de la Base de Datos (MySQL)
# Si Railway inyecta MYSQL_URL la usará; de lo contrario, usará tu localhost en el puerto 3307
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3307/voley_strategy?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. Seguridad JWT
# En Railway puedes crear una variable llamada JWT_SECRET para no dejar tu clave expuesta en GitHub
jwt.secret=${JWT_SECRET:bibliotecaduoc-clave-secreta-jwt-2026-cambiar-en-produccion}